fixed blocked mixed content
ERROR: jquery not loaded

FIX:
updated CDN links for jquery which delivered content via
HTTP, getting blocked in the process. This fix is important
since the app will be hosted on heroku that deliveres HTTPS
pages.